"""
Cisco IOS-XR Automation Module for NetPilot AI.

Future Enhancements:
- NETCONF/YANG operations
- BGP/ISIS/MPLS automation
- XR-specific configuration templates
"""

from typing import List

def generate_interface_config(interfaces: List[str]) -> str:
    """
    Generate a basic interface configuration template for Cisco IOS-XR devices.
    """

    lines = ["! Configuration generated by NetPilot AI (Cisco IOS-XR)"]

    for iface in interfaces:
        lines.append(f"interface {iface}")
        lines.append(" description Managed by NetPilot AI")
        lines.append(" no shutdown")
        lines.append("!")

    return "\n".join(lines)
