"""
Cisco IOS-XE Automation Module for NetPilot AI.

Future Enhancements:
- RESTCONF-based configuration push
- NETCONF/YANG automation
- Device onboarding
- Template-based configuration generation
"""

from typing import List

def generate_interface_config(interfaces: List[str]) -> str:
    """
    Generate simple interface configuration blocks for Cisco IOS-XE devices.

    Example:
        interfaces = ["GigabitEthernet1", "GigabitEthernet2"]
    """

    lines = ["! Configuration generated by NetPilot AI (Cisco IOS-XE)"]

    for iface in interfaces:
        lines.append(f"interface {iface}")
        lines.append(" description Managed by NetPilot AI")
        lines.append(" no shutdown")
        lines.append("!")

    return "\n".join(lines)
