"""
Cisco NX-OS Automation Module for NetPilot AI.

Future Enhancements:
- NX-API REST calls
- CLI-based configuration push (SSH)
- Template-based L2/L3 configuration
- Support for vPC, VLAN, VRF, OSPF, BGP
"""

from typing import List

def generate_interface_config(interfaces: List[str]) -> str:
    """
    Generate a basic interface configuration template for Cisco NX-OS devices.
    """

    lines = ["! Configuration generated by NetPilot AI (Cisco NX-OS)"]

    for iface in interfaces:
        lines.append(f"interface {iface}")
        lines.append(" description Managed by NetPilot AI")
        lines.append(" no shutdown")
        lines.append("!")

    return "\n".join(lines)
