"""
Aruba Networks Automation Module for NetPilot AI.

Supports future automation for:
- Aruba AOS-CX switches
- Aruba Wireless (Central API)
- VLAN, interface, and routing configuration
- Template-driven provisioning
"""

from typing import List

def generate_interface_config(interfaces: List[str]) -> str:
    """
    Generate basic interface configuration for Aruba AOS-CX.
    """

    lines = ["! Configuration generated by NetPilot AI (Aruba AOS-CX)"]

    for iface in interfaces:
        lines.append(f"interface {iface}")
        lines.append("    description Managed by NetPilot AI")
        lines.append("    no shutdown")
        lines.append("!")
    
    return "\n".join(lines)
