"""
Juniper JunOS Automation Module for NetPilot AI.

Future Enhancements:
- NETCONF/YANG with ncclient
- RPC operations
- Template-based configuration rendering
- Full device onboarding logic
"""

from typing import List

def generate_interface_config(interfaces: List[str]) -> str:
    """
    Generate JunOS-style interface configuration.
    """

    lines = ["## Generated by NetPilot AI (Juniper JunOS)"]

    for iface in interfaces:
        lines.append(f"interfaces {{")
        lines.append(f"    {iface} {{")
        lines.append(f"        description \"Managed by NetPilot AI\";")
        lines.append(f"        unit 0 {{")
        lines.append(f"            family inet;")
        lines.append(f"        }}")
        lines.append(f"    }}")
        lines.append(f"}}")
        lines.append("")

    return "\n".join(lines)
