"""
Arista EOS Automation Module for NetPilot AI.

Future Enhancements:
- eAPI automation using JSON-RPC
- VLAN, VXLAN, MLAG automation
- Switch onboarding
- Template-based configuration generation
"""

from typing import List

def generate_interface_config(interfaces: List[str]) -> str:
    """
    Generate simple interface configuration for Arista EOS.
    """

    lines = ["! Configuration generated by NetPilot AI (Arista EOS)"]

    for iface in interfaces:
        lines.append(f"interface {iface}")
        lines.append("   description Managed by NetPilot AI")
        lines.append("   no shutdown")
        lines.append("!")
    
    return "\n".join(lines)
